website/models.py
from . import db
from flask_login import UserMixin
from datetime import datetime
from pytz import timezone

def shanghai_time():
    now_utc=datetime.now(timezone('UTC'))
    now_shanghai=now_utc.astimezone(timezone('Asia/Shanghai'))
    return now_shanghai.strftime('%Y年%m月%d日 %H:%M')



class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    username = db.Column(db.String(300), unique=True)
    password = db.Column(db.String(100), unique=True)
    posts = db.relationship('Post', backref='user', passive_deletes=True)


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(150))
    content = db.Column(db.Text, nullable=False)
    author = db.Column(db.Integer, db.ForeignKey(
        'user.id', ondelete='CASCADE'), nullable=False)
    comments = db.relationship('Comment', backref='post', passive_deletes=True)
    created_time = db.Column(db.String(200),default=shanghai_time)

class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.String(300), nullable=False)
    author = db.Column(db.Integer, db.ForeignKey(
        'user.id', ondelete='CASCADE'), nullable=False)
    author_name=db.Column(db.String(300))
    article = db.Column(db.Integer, db.ForeignKey('post.id', ondelete='CASCADE'), nullable=False)
    created_time = db.Column(db.String(200),default=shanghai_time)

website/__init__.py
from os import path
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_ckeditor import CKEditor
from flask_moment import Moment

BASEDIR = path.abspath(path.dirname(__file__))
# DB_NAME = 'database.db'

db = SQLAlchemy()
ckeditor=CKEditor()
moment=Moment()


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'Simon Yen'
    # app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    app.config['SQLALCHEMY_DATABASE_URI']='something'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True
    app.config['SQLALCHEMY_COMMIT_TEARDOWN'] = True
    app.config['MDEDITOR_FILE_UPLOADER'] = path.join(BASEDIR, 'editor_cache')
    db.init_app(app)
    ckeditor.init_app(app)
    moment.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views)
    app.register_blueprint(auth)

    from .models import User

    db.create_all(app=app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


# def create_database(app):
#     if not path.exists('website/'+DB_NAME):
#         db.create_all(app=app)
#         print('已创建数据库！')

website/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from .models import User

auth = Blueprint("auth", __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('登录成功。', category='success')
                if request.form.get('remember') == 'on':
                    login_user(user, remember=True)
                else:
                    login_user(user, remember=False)
                return redirect(url_for('views.home'))
            else:
                flash('密码错误！', category='error')
        else:
            flash('邮箱不存在！', category='info')
    return render_template('login.html', user=current_user)


@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        email = request.form.get('email')
        username = request.form.get('username')
        password = request.form.get('password')
        password_confirm = request.form.get('password-confirm')

        email_exists = User.query.filter_by(email=email).first()
        if email_exists:
            flash('邮箱已被注册！', category='error')
        elif password != password_confirm:
            flash('重复密码不一致！', category='error')
        elif len(username) < 2:
            flash('用户名长度太短了！', category='error')
        elif len(password) < 5:
            flash('密码必须大于5个字符！', category='error')
        else:
            new_user = User(email=email, username=username, password=generate_password_hash(
                password=password, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            flash('成功创建账号。', category='success')
            return redirect(url_for('auth.login'))

    return render_template('signup.html', user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for("views.home"))

website/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from . import db
from .models import Post,Comment

views = Blueprint("views", __name__)


@views.route('/')
def home():
    return render_template('home.html', user=current_user)

@views.route('/square')
def square():
    posts = Post.query.all()
    posts.reverse()
    return render_template('square.html',posts=posts,user=current_user)

@views.route('/my_posts')
@login_required
def my_posts():
    posts=Post.query.filter_by(author=current_user.id).all()
    posts.reverse()
    return render_template('square.html', user=current_user, posts=posts)



@views.route('/create_post', methods=['POST', 'GET'])
@login_required
def create_post():
    if request.method == 'POST':
        title = request.form.get('title')
        content = request.form.get('ckeditor')
        if not content:
            flash('帖子内容为空！', category='error')
        else:
            new_post = Post(title=title, content=content,
                            author=current_user.id)
            db.session.add(new_post)
            db.session.commit()
            flash('帖子创建成功。', category='success')
            return redirect(url_for('views.home'))
    return render_template('create_post.html', user=current_user)


@views.route('/view_post/<id>',methods=['POST','GET'])
def view_post(id):
    p = Post.query.filter_by(id=id).first()
    comments=Comment.query.filter_by(article=id).all()
    if request.method == 'POST':
        if not current_user.is_authenticated:
            flash('请先登录再评论他人帖子！')
        else:
            content=request.form.get('comment')
            c=Comment(content=content,author=current_user.id,article=p.id,author_name=current_user.username)
            db.session.add(c)
            db.session.commit()
            flash('评论成功。')
            return redirect(url_for('views.view_post', id=p.id))
    return render_template('view_post.html', post=p , user=current_user , comments=comments)

@views.route('/motify_post/<id>', methods=['POST', 'GET'])
@login_required
def motify_post(id):
    p = Post.query.filter_by(id=id).first()
    if request.method=='POST':
        if p.author!=current_user.id:
            flash('你无权修改他人的帖子！')
        else:
            p.title = request.form.get('title')
            p.content = request.form.get('ckeditor')
            db.session.commit()
            flash('帖子修改成功。')
            return redirect(url_for('views.view_post',id=p.id))
    return render_template('motify_post.html',post=p,user=current_user)



@views.route('/delete_post/<id>')
@login_required
def delete_post(id):
    p = Post.query.filter_by(id=id).first()
    if not p:
        flash('所删除的帖子不存在！', category='info')
    else:
        if p.author != current_user.id:
            flash('你无权限删除别人的帖子！', category='error')
        else:
            db.session.delete(p)
            db.session.commit()
            flash('删除成功。', category='sucess')
            return redirect(url_for('views.home'))

@views.route('/about')
def about():
    return render_template('about.html', user=current_user)

website/templates/about.html
{% extends 'base.html' %}
{% block title %}
浮世草
{% endblock %}
{% block content %}
<section class="hero is-danger">
	<div class="hero-body">
		<p class="title">
			颜曾一
		</p>
		<p class="subtitle">
			英文名Simon Yen
		</p>
	</div>
</section>
<section class="hero is-success">
	<div class="hero-body">
		<p class="title">
			身份
		</p>
		<p class="subtitle">
			双非菜鸡研究生
		</p>
	</div>
</section>
<section class="hero is-warning">
	<div class="hero-body">
		<p class="title">
			技术栈
		</p>
		<p class="subtitle">
			熟悉golang，python，稍微了解rust。
		</p>
	</div>
</section>
<section class="hero is-info">
	<div class="hero-body">
		<p class="title">
			联系方式
		</p>
		<p class="subtitle">
			邮箱：simonyen@foxmail.com QQ：2154571392
		</p>
	</div>
</section>
{% endblock %}

website/templates/base.html
<!doctype html>
<html lang="zh-CN">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
	<link rel="stylesheet"
		href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.5.5/css/simple-line-icons.min.css">
	<style>
		body {
			background-image: url("{{url_for('static', filename='white.png')}}");
			background-color: #cccccc;
		}

		nav {
			background-image: url("{{url_for('static', filename='flowers.png')}}");
			background-color: #cccccc;
		}
	</style>
	<title>
		{% block title %}
		迷你博客
		{% endblock %}
	</title>
</head>

<body>
	<nav id="top" class="navbar is-light has-shadow" role="navigation" aria-label="main navigation">
		<div class="navbar-brand">
			<a class="navbar-item" href="{{ url_for('views.home' ) }}">
				<img src="{{ url_for('static' , filename = 'logo.png') }}">
			</a>
			<a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false"
				data-target="navbarBasicExample">
				<span aria-hidden="true"></span>
				<span aria-hidden="true"></span>
				<span aria-hidden="true"></span>
			</a>
		</div>

		<div id="navbarBasicExample" class="navbar-menu">
			<div class="navbar-start">
				<a class="navbar-item" href="{{ url_for('views.square') }}">
					<span class="icon-magic-wand"></span>广场
				</a>
				{% if user.is_authenticated %}
				<a class="navbar-item" href="{{ url_for('views.create_post' ) }}">
					<span class="icon-plus"></span>新建帖子
				</a>
				<a class="navbar-item" href="{{ url_for('views.my_posts' ) }}">
					<span class="icon-mustache"></span>我的帖子
				</a>
				{% endif %}
				<a class="navbar-item" href="{{ url_for('views.about' ) }}">
					<span class="icon-ghost"></span>关于作者
				</a>
			</div>

			<div class="navbar-end">
				<div class="navbar-item">
					<div class="buttons">
						{% if user.is_authenticated %}
						<a href="{{ url_for('auth.logout' ) }}" class="button is-danger"><span
								class="icon-logout"></span>登出</a>
						{% else %}
						<a class="button is-primary" href="{{ url_for('auth.signup' ) }}">
							<span class="icon-user"></span><strong>注册</strong>
						</a>
						<a class="button is-info" href="{{ url_for('auth.login' ) }}">
							<span class="icon-login"></span>登录
						</a>

						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</nav>
	{% for message in get_flashed_messages() %}
	<div class="notification is-warning">
		<button class="delete"></button>
		{{message}}
	</div>
	{% endfor %}
	<section class="section">
		{% block content %}

		{% endblock %}
	</section>
	<div class="block"></div>
	<footer class="footer">
		<div class="content has-text-centered">
			<p>
				<strong>迷你博客</strong>由
				<a href="https://github.com/SimonYen">
					<span class="icon-social-github"></span>Simon Yen
				</a>编写，欢迎
				<a href="https://github.com/SimonYen/Mini-Blog">
					<span class="icon-star"></span>
				</a>！
			</p>
		</div>
	</footer>
	<script>
		document.addEventListener('DOMContentLoaded', () => {
			(document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
				const $notification = $delete.parentNode;

				$delete.addEventListener('click', () => {
					$notification.parentNode.removeChild($notification);
				});
			});
		});
	</script>
	<script>
		(function () {
			var burger = document.querySelector('.nav-toggle');
			var menu = document.querySelector('.nav-menu');
			burger.addEventListener('click', function () {
				burger.classList.toggle('is-active');
				menu.classList.toggle('is-active');
			});
		})();
	</script>
	<script>
		document.addEventListener('DOMContentLoaded', () => {

			// Get all "navbar-burger" elements
			const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

			// Check if there are any navbar burgers
			if ($navbarBurgers.length > 0) {

				// Add a click event on each of them
				$navbarBurgers.forEach(el => {
					el.addEventListener('click', () => {

						// Get the target from the "data-target" attribute
						const target = el.dataset.target;
						const $target = document.getElementById(target);

						// Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
						el.classList.toggle('is-active');
						$target.classList.toggle('is-active');

					});
				});
			}

		});
	</script>
	{{ ckeditor.load() }}
</body>

</html>

website/templates/check_post.html
{% extends 'base.html' %}
{% block title %}
{{post.title}}
{% endblock %}
{% block content %}
<div class="box">
	<div class="content">
		<h1 class="title">{{post.title}}</h1>
		<h2 class="subtitle">
			<span class="tag is-info">作者：{{post.user.username}}</span>
			<span class="tag is-success">创作时间：{{post.date_created}}</span>
		</h2>
	</div>
</div>
<div class="box">
	{{post.content|markdown|safe}}
</div>
{% endblock %}

website/templates/create_post.html
{% extends 'base.html' %}
{% block title %}
新建帖子
{% endblock %}
{% block content %}
<div class="box">
	<form method="post">
		<input class="input is-medium" type="text" placeholder="标题" name="title">
		{{ ckeditor.create() }}
		<div class="field is-grouped is-grouped-right">
			<button class="button is-medium is-warning ">
				<span class="icon-cloud-upload"></span>提交
			</button>
		</div>
	</form>
</div>
{% endblock %}

website/templates/home.html
{% extends 'base.html' %}

{% block title %}
迷你博客-主页
{% endblock %}

{% block content %}
<div class="content is-large">
	<h1>迷你博客</h1>
	<p>一个基于Flask框架编写的小清新博客网站，前端用的CSS框架是Bulma。</p>
	<p>只具有基础的博客增删查改功能，主要是为了让我入门web开发的。</p>
	<p>同时我也想把这个网站当成我的一个学习博客，温故知新。</p>
	<p>希望能惊艳到你~</p>
</div>
{% endblock %}

website/templates/login.html
{% extends 'base.html' %}
{% block title %}
迷你博客-登录
{% endblock %}
{% block content %}
<div class="box">
	<form method="post">
		<div class="field">
			<label class="label">
				<span class="icon-envelope"></span>电子邮箱
			</label>
			<p class="control">
				<input class="input" type="email" placeholder="邮箱地址" name="email">
			</p>
		</div>
		<div class="field">
			<label class="label">
				<span class="icon-lock"></span>密码
			</label>
			<p class="control">
				<input class="input" type="password" placeholder="密码" name="password">
			</p>
		</div>
		<label class="checkbox">
			<input type="checkbox" name="remember">
			<strong>记住我</strong>
		</label>
		<div class="field is-grouped is-grouped-right">
			<button class="button is-primary">
				<span class="icon-paper-plane"></span>登录
			</button>
		</div>
	</form>
</div>
{% endblock %}

website/templates/motify_post.html
{% extends 'base.html' %}
{% block title %}
新建帖子
{% endblock %}
{% block content %}
<div class="box">
	<form method="post">
		<input class="input is-medium" type="text" placeholder="标题" name="title" value="{{post.title}}">
		{{ ckeditor.create(value=post.content) }}
		<button class="button is-medium is-warning ">
			<span class="icon-cloud-upload"></span>提交
		</button>
	</form>
</div>
{% endblock %}

website/templates/signup.html
{% extends 'base.html' %}
{% block title %}
轻博客-注册
{% endblock %}
{% block content %}
<div class="box">
	<form method="post">
		<div class="field">
			<label class="label">
				<span class="icon-envelope"></span>电子邮箱
			</label>
			<p class="control">
				<input class="input" type="email" placeholder="邮箱地址" name="email">
			</p>
		</div>
		<div class="field">
			<label class="label">
				<span class="icon-mustache"></span>用户名
			</label>
			<p class="control">
				<input class="input" type="text" placeholder="用户名" name="username">
			</p>
		</div>
		<div class="field">
			<label class="label">
				<span class="icon-lock"></span>密码
			</label>
			<p class="control">
				<input class="input" type="password" placeholder="密码" name="password">
			</p>
		</div>
		<div class="field">
			<label class="label">
				<span class="icon-reload"></span>确认密码
			</label>
			<p class="control">
				<input class="input" type="password" placeholder="再次输入密码" name="password-confirm">
			</p>
		</div>
		<div class="field is-grouped is-grouped-right">
			<button class="button is-primary">
				<span class="icon-plane"></span>注册
			</button>
		</div>
	</form>
</div>
{% endblock %}

website/templates/square.html
{% extends 'base.html' %}
{% block title %}
迷你博客-广场
{% endblock %}

{% block content %}
{% for post in posts %}
<div class="card">
	<header class="card-header">
		<p class="card-header-title">
			<span class="icon-cup"></span>{{post.title}}
		</p>
	</header>
	<div class="card-content">
		<div class="content">
			<h1 class="title">
				<span class="tag is-info">作者：{{post.user.username}}</span>
			</h1>
			<h2 class="subtitle">
				<span class="tag is-success">创作时间：{{post.created_time}}</span>
			</h2>
			<div class="field is-grouped is-grouped-right">
				<div class="buttons are-medium">
					<a class="button is-primary is-light" href="{{ url_for('views.view_post' , id =  post.id) }}"><span
							class="icon-book-open"></span>查看</a>
					{% if user.id == post.author %}
					<a class="button is-link is-light" href="{{ url_for('views.motify_post' , id = post.id) }}"><span
							class="icon-pencil"></span>修改</a>
					<a class="button is-danger is-light" href="{{ url_for('views.delete_post' , id = post.id) }}"><span
							class="icon-minus"></span>删除</a>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</div>
<div class="block"></div>
{% endfor %}
<div class="field is-grouped is-grouped-centered">
	<a href="#top" class="button is-medium">回到顶部</a>
</div>
{% endblock %}

website/templates/view_post.html
{% extends 'base.html' %}
{% block title %}
{{post.title}}
{% endblock %}
{% block content %}
<div class="content is-large">
	<h1 class="title">{{post.title}}</h1>
	<h2 class="subtitle">
		<span class="tag is-info">作者：{{post.user.username}}</span>
		<span class="tag is-success">创作时间：{{post.created_time}}</span>
	</h2>
	<h3>
		<span class="tag is-link is-large">内容：</span>
	</h3>
	{{post.content|safe}}
</div>
<span class="tag is-warning is-light is-light">评论：</span>
{% for comment in comments %}
<div class="content is-small">
	<h1>{{comment.author_name}}</h1>
	<p>{{comment.content}}</p>
</div>
{% endfor %}
<hr>
{% if user.is_authenticated %}
<div class="box">
	<article class="media">
		<div class="media-content">
			<form method="post">
				<div class="field">
					<p class="control">
						<textarea class="textarea" placeholder="说句骚话评论吧。。。" name="comment" required></textarea>
					</p>
				</div>
				<div class="field is-grouped is-grouped-right">
					<button class="button is-medium is-info">
						<span class="icon-feed"></span>评论
					</button>
				</div>
			</form>
		</div>
	</article>
</div>
{% endif %}
<div class="field is-grouped is-grouped-centered">
	<a href="#top" class="button is-medium">回到顶部</a>
</div>
{% endblock %}